version: '3.2'
services:

###################
# NEXTCLOUD STACK #
###################
  app:
    image: nextcloud:25
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 8080:80
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
    networks:
      - default

  db:
    image: mariadb:10
    restart: always
    security_opt:
      - no-new-privileges:true
    command: ['--innodb_read_only_compressed=OFF']
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      
volumes:
  nextcloud_data:
  db_data:
